Repository NOAA-OWP/ras2fim, pull requests merged in 2023-08, with the labels that each got.

#115 [2pt] Change default output folder name and disable ras2rem by default
  doc/CHANGELOG.md
  doc/INSTALL.md
  src/clip_dem_from_shape.py
  src/convert_tif_to_ras_hdf5.py
  src/create_fim_rasters.py
  src/get_usgs_dem_from_shape.py
  src/ras2fim.py
  src/run_ras2rem.py
  src/shared_functions.py
  src/shared_validators.py
  src/simplify_fim_rasters.py
  src/worker_fim_rasters.py
  tools/convert_ras2fim_to_recurr_validation_datasets.py
  tools/get_ras_models_by_catalog.py
Labels: bug, enhancement, ras2fim, high priority

#101 [1pt] PR: stop the code if there is no conflated model
  doc/CHANGELOG.md
  src/conflate_hecras_to_nwm.py
  src/errors.py
Labels: bug, ras2fim

#126 [1pt] PR: Add WSE to rating curves in ras2fim, updates to rating curve compilation script (unit handling, projection, and functioning without ras2rem)
  doc/CHANGELOG.md
  src/reformat_ras_rating_curve.py
  src/simplify_fim_rasters.py
  src/worker_fim_rasters.py
Labels: ras2fim, high priority

#128 [1pt] PR: Rating Curve Error
  doc/CHANGELOG.md
  src/reformat_ras_rating_curve.py
  src/simplify_fim_rasters.py
  src/worker_fim_rasters.py
Labels: bug, ras2fim, low priority

#135 [5pt] PR: get cross sections info and finalized standardization of rating curves
  doc/CHANGELOG.md
  src/shared_variables.py
  src/simplify_fim_rasters.py
  src/worker_fim_rasters.py
Labels: enhancement, ras2fim

#134 [1pt] PR: HEC-RAS windows left open on HEC-RAS errors
  doc/CHANGELOG.md
  src/create_shapes_from_hecras.py
  src/worker_fim_rasters.py
Labels: bug, ras2fim, high priority

#142 [1pt] PR: Add config system
  .gitignore
  config/r2f_config.env
  doc/CHANGELOG.md
  environment.yml
  src/calculate_all_terrain_stats.py
  src/clip_dem_from_shape.py
  src/conflate_hecras_to_nwm.py
  src/create_shapes_from_hecras.py
  src/ras2catchments.py
  src/ras2fim.py
  src/reformat_ras_rating_curve.py
  src/run_ras2rem.py
  src/shared_functions.py
  src/shared_variables.py
  src/simplify_fim_rasters.py
  src/worker_fim_rasters.py
  tools/convert_ras2fim_to_recurr_validation_datasets.py
  tools/nws_ras2fim_post_frequency_grid.py
Labels: enhancement, ras2fim, high priority

#140 [1pt] PR: Adds geocurve and canned inundation production capabilities
  config/r2f_config.env
  doc/CHANGELOG.md
  src/create_geocurves.py
  src/ras2fim.py
  src/ras2inundation.py
  src/run_ras2rem.py
  src/shared_functions.py
Labels: enhancement

#139 [1pt] PR: Integrate ras2calibration into ras2fim.py
  config/r2f_config.env
  doc/CHANGELOG.md
  src/ras2fim.py
  src/reformat_ras_rating_curve.py
  src/shared_variables.py
Labels: ras2fim

#151 [5pt] PR: create polygons for ras models domain
  config/r2f_config.env
  doc/CHANGELOG.md
  src/create_model_domain_polygons.py
  src/ras2fim.py
  src/shared_variables.py
Labels: enhancement, ras2fim
